---
# handlers file for prometheus
  - name: restart prometheus
    service: name=prometheus state=restarted enabled=yes

  - name: restart alertmanager
    service: name=alertmanager state=restarted enabled=yes

  - name: restart node_exporter
    service: name=node_exporter state=restarted enabled=yes

  - name: restart grafana
    service: name=grafana-server state=restarted enabled=yes

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
