---
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: Install Graphite, apache2 and postgres
    apt: name={{item}} state=present
    with_items:
      - graphite-web
      - graphite-carbon
      - postgresql
      - libpq-dev
      - python-psycopg2
      - apache2
      - libapache2-mod-wsgi
    register: graphite_installation

#  - name: make db folder for postgres
#    file: path=/data/postgresql state=directory owner=postgres group=postgres mode=0755

  - name: copying postgresql.conf
    copy: src=postgresql.conf dest=/etc/postgresql/9.5/main/postgresql.conf owner=postgres group=postgres mode=0644 force=yes
    when: graphite_installation
    notify: restart postgres

  - name: initdb postgres
    shell: /usr/lib/postgresql/9.5/bin/initdb -D /data/postgresql/
    become: yes
    become_user: postgres
    ignore_errors: yes

  - name: create postgres user
    postgresql_user: name=graphite_user password={{postgres_user_password}} state=present
    become: true
    become_user: postgres

  - name: create postgres db for graphite
    postgresql_db: name=graphite_db state=present owner=graphite_user
    become: true
    become_user: postgres

  - name: create postgres db for grafana
    postgresql_db: name=grafana_db state=present owner=graphite_user
    register: postgres_configuration
    become: true
    become_user: postgres

  - name: create db directory for whisper
    file: path=/data/graphite/whisper state=directory owner=_graphite group=_graphite mode=0755

  - name: copy local_settings.py
    template: src=local_settings.py dest=/etc/graphite/local_settings.py owner=root group=root mode=0644 force=yes

  - name: copy carbon.conf
    copy: src=carbon.conf dest=/etc/carbon/carbon.conf owner=root group=root mode=0644 force=yes

  - name: doing graphite migration
    shell: cd /usr/lib/python2.7/dist-packages/graphite/; python manage.py migrate auth; python manage.py migrate;

  - name: graphite syncdb
    shell: graphite-manage syncdb --noinput

  - name: copying storage-aggregation.conf
    shell: cp /usr/share/doc/graphite-carbon/examples/storage-aggregation.conf.example /etc/carbon/storage-aggregation.conf
    notify: restart carbon-cache

  - name: copying graphite-carbon
    copy: src=graphite-carbon dest=/etc/default/graphite-carbon

  - name: copying storage-schemas.conf
    copy: src=storage-schemas.conf dest=/etc/carbon/storage-schemas.conf owner=root group=root mode=0644 force=yes
    when: collectd_installation
    notify: restart carbon-cache


  - name: configuring apache2
    shell: a2dissite 000-default; cp /usr/share/graphite-web/apache2-graphite.conf /etc/apache2/sites-available; a2ensite apache2-graphite; service apache2 reload
    register: graphite_done
    ignore_errors: yes
